service: alexa-whats-on

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  stage: production
  tracing: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource:
        - "*"

package:
  artifact: alexa-whats-on.jar

functions:
  whats-on:
    handler: io.igu.whatson.WhatsOnLambda
    events:
      - alexaSkill

plugins:
  - serverless-plugin-tracing
